version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8893:8893"
    volumes:
      - ./app:/var/www/bitrix
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    links:
      - app
    networks:
      - oebackend
  app:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/bitrix
    networks:
      - oebackend
  cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/var/www/bitrix
    networks:
      - oebackend
    tty: true
  db:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - oebackend

  redis:
    build: ./docker/redis
    ports:
      - '6379:6379'
    networks:
      - oebackend

  elasticsearch:
    build:
      context: ./docker/elasticsearch
    ports:
      - "9200:9200"
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker/elasticsearch/data:/var/lib/elasticsearch/data
    networks:
      - oebackend
  kibana:
    build:
      context: ./docker/kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - oebackend

  push-server-sub:
    image: ikarpovich/bitrix-push-server
    links:
      - redis
    depends_on:
      - redis
    networks:
      - oebackend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LISTEN_HOSTNAME=0.0.0.0
      - LISTEN_PORT=80
      - SECURITY_KEY=testtesttest
      - MODE=sub
    ports:
      - '8081:80'

  push-server-pub:
    image: ikarpovich/bitrix-push-server
    links:
      - redis
    depends_on:
      - redis
    networks:
      - oebackend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LISTEN_HOSTNAME=0.0.0.0
      - LISTEN_PORT=80
      - SECURITY_KEY=testtesttest
      - MODE=pub
    ports:
      - '8082:80'

networks:
  oebackend:
    driver: bridge
